build:
  stage: build
  image: rbonifaz/wahay-rpm-build:latest
  before_script:
    - "eval $(ssh-agent -s)"
    - 'ssh-add <(echo "$FEDORA_PACKAGING_PRIVATE_KEY")'
    - mkdir -p ~/.ssh; chmod 700 ~/.ssh
    - 'echo -e "[fedora.autonomia.digital]:4243,[185.108.78.22]:4243 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFE8IPu1LfB0ePyhgBFTyzXRNBZUiYa1ZaSnkFb746r3MgZQlfMhfxdMtrY3bKoiQ4i+HEUTCUN4BJ5n2PMdGz4=" > ~/.ssh/known_hosts'
    - chmod 644 ~/.ssh/known_hosts

  script:
    - git clone https://github.com/cubiest/jibberjabber.git jibberjabber-2.1
    - cd jibberjabber-2.1/
    - git checkout tags/v2.1
    - cd ..
    - tar zcf jibberjabber-2.1.tar.gz jibberjabber-2.1
    - mkdir f30 f31 f32 f33 f34 f35 f36 f37 f38
    - fedpkg --release f30 local
    - 'find . -name "*fc30*.rpm" -exec cp {} f30/ \;'
    - fedpkg --release f31 local
    - 'find . -name "*fc31*.rpm" -exec mv {} f31/ \;'
    - fedpkg --release f32 local
    - 'find . -name "*fc32*.rpm" -exec mv {} f32/ \;'
    - fedpkg --release f33 local
    - 'find . -name "*fc33*.rpm" -exec mv {} f33/ \;'
    - fedpkg --release f34 local
    - 'find . -name "*fc34*.rpm" -exec mv {} f34/ \;'
    - fedpkg --release f35 local
    - 'find . -name "*fc35*.rpm" -exec mv {} f35/ \;'
    - fedpkg --release f36 local
    - 'find . -name "*fc36*.rpm" -exec mv {} f36/ \;'
    - fedpkg --release f37 local
    - 'find . -name "*fc37*.rpm" -exec mv {} f37/ \;'
    - fedpkg --release f38 local
    - 'find . -name "*fc38*.rpm" -exec mv {} f38/ \;'
    - 'scp -r -P4243 f30/* fedora-repo@fedora.autonomia.digital:packages/upload/f30'
    - 'scp -r -P4243 f31/* fedora-repo@fedora.autonomia.digital:packages/upload/f31'
    - 'scp -r -P4243 f32/* fedora-repo@fedora.autonomia.digital:packages/upload/f32'
    - 'scp -r -P4243 f33/* fedora-repo@fedora.autonomia.digital:packages/upload/f33'
    - 'scp -r -P4243 f34/* fedora-repo@fedora.autonomia.digital:packages/upload/f34'
    - 'scp -r -P4243 f35/* fedora-repo@fedora.autonomia.digital:packages/upload/f35'
    - 'scp -r -P4243 f36/* fedora-repo@fedora.autonomia.digital:packages/upload/f36'
    - 'scp -r -P4243 f37/* fedora-repo@fedora.autonomia.digital:packages/upload/f37'
    - 'scp -r -P4243 f38/* fedora-repo@fedora.autonomia.digital:packages/upload/f38'

  artifacts:
    paths:
      - 'f3*/*.rpm'
